export type FreeSurferStructure = {
  value: number;
  name: string;
};

export const FREESURFER_STRUCTURES: FreeSurferStructure[] = [
  { value: 2,   name: "Left-Cerebral-White-Matter" },
  { value: 3,   name: "Left-Cerebral-Cortex" },
  { value: 4,   name: "Left-Lateral-Ventricle" },
  { value: 5,   name: "Left-Inf-Lat-Vent" },
  { value: 7,   name: "Left-Cerebellum-White-Matter" },
  { value: 8,   name: "Left-Cerebellum-Cortex" },
  { value: 10,  name: "Left-Thalamus" },
  { value: 11,  name: "Left-Caudate" },
  { value: 12,  name: "Left-Putamen" },
  { value: 13,  name: "Left-Pallidum" },
  { value: 14,  name: "3rd-Ventricle" },
  { value: 15,  name: "4th-Ventricle" },
  { value: 16,  name: "Brain-Stem" },
  { value: 17,  name: "Left-Hippocampus" },
  { value: 18,  name: "Left-Amygdala" },
  { value: 24,  name: "CSF" },
  { value: 26,  name: "Left-Accumbens-area" },
  { value: 28,  name: "Left-VentralDC" },
  { value: 30,  name: "Left-vessel" },
  { value: 31,  name: "Left-choroid-plexus" },
  { value: 41,  name: "Right-Cerebral-White-Matter" },
  { value: 42,  name: "Right-Cerebral-Cortex" },
  { value: 43,  name: "Right-Lateral-Ventricle" },
  { value: 44,  name: "Right-Inf-Lat-Vent" },
  { value: 46,  name: "Right-Cerebellum-White-Matter" },
  { value: 47,  name: "Right-Cerebellum-Cortex" },
  { value: 49,  name: "Right-Thalamus" },
  { value: 50,  name: "Right-Caudate" },
  { value: 51,  name: "Right-Putamen" },
  { value: 52,  name: "Right-Pallidum" },
  { value: 53,  name: "Right-Hippocampus" },
  { value: 54,  name: "Right-Amygdala" },
  { value: 58,  name: "Right-Accumbens-area" },
  { value: 60,  name: "Right-VentralDC" },
  { value: 62,  name: "Right-vessel" },
  { value: 63,  name: "Right-choroid-plexus" },
  { value: 72,  name: "5th-Ventricle" },
  { value: 77,  name: "WM-hypointensities" },
  { value: 78,  name: "Left-WM-hypointensities" },
  { value: 79,  name: "Right-WM-hypointensities" },
  { value: 80,  name: "non-WM-hypointensities" },
  { value: 81,  name: "Left-non-WM-hypointensities" },
  { value: 82,  name: "Right-non-WM-hypointensities" },
  { value: 85,  name: "Optic-Chiasm" },
  { value: 251, name: "CC_Posterior" },
  { value: 252, name: "CC_Mid_Posterior" },
  { value: 253, name: "CC_Central" },
  { value: 254, name: "CC_Mid_Anterior" },
  { value: 255, name: "CC_Anterior" },
];
